import '~/sass/library/library.scss'
import '~/sass/main.sass'
import '~/scripts/index.js'
// import './scripts/number'
// import './scripts/string'
// import './scripts/TemplateString'
// import './scripts/object'
// import './scripts/1.2/condoperators'
// import './scripts/1.2/switchCase'
// import './scripts/1.2/for'
// import './scripts/1.2/function'
// import './scripts/1.2/methodMassive'
// import './scripts/1.3/recurse'
// import './scripts/1.3/higher order functions'
// import './scripts/1.3/closure'
// import './scripts/1.3/filter'
// import './scripts/1.3/this'
// import './scripts/1.4/arrow function'
// import './scripts/1.4/iterating array methods'
// import './scripts/2.0/metods object'
// import './scripts/2.0/spreadRest'
// import './scripts/2.0/destruct'
// import './scripts/2.0/map'
// import './scripts/2.0/set'
// import './scripts/2.0/2.2/date'
import './scripts/2.0/2.3/prototype'
